### ISSUE TITLE
Create new artifact action to log a message 

### ISSUE THREAD

**Issue by stmh** [factorial-io/phabalicious#109]
sth like
```yaml
  actions:
    - action: log
      arguments:
       severity: (debug|info|notice|warning|error)
       message: My important log message
```
Should mimic the existing script_callback `log_message`
