### ISSUE TITLE
beta5: booleans get converted to strings when using `alter_yaml_file`

### ISSUE THREAD

**Issue by mgrsskls** [factorial-io/phabalicious#141]
When using the latest beta (5), `alter_yaml_file` converts booleans to strings:

```yaml
grumphp:
  tasks:
    npm_script:
      is_run_task: true
```
becomes
```yaml
grumphp:
  tasks:
    npm_script:
      is_run_task: '1'
```
In this case `grumphp` will throw an error.
