### ISSUE TITLE
support multiple 1password connect tokens

### ISSUE THREAD

**Issue by stmh** [factorial-io/phabalicious#156]
Currently only on 1password connect JWT token is supported. It would be great if more than one configuration can be handled by phab.

e.g.

```
secret:
  one:
    onePasswordId: xxx
    onePasswordVaultId: xxx
    token: token-1

...
onePassword:
  token-1:
    endpoint: https://xxx.yz
    token: zzz
  token-2:
    endpoint: https://xxx.zz
    token: aaa
```
