### ISSUE TITLE
CopyAction special handling of * does not apply to multiple 'from' arguments

### ISSUE THREAD

**Issue by mikran** [factorial-io/phabalicious#157]
I'm not sure if this is bug or feature request, but following configuration had unexpected outcome

```yml
- action: copy
  arguments:
    from:
      - "archive-a/sites/default/files/*"
      - "archive-b/sites/default/files/*"
    to: "./sites/default/files/"
```

I was expecting to add files from both archive-a and archive-b to whatever happened to be in files dir already from previous operations.

This works like that when I have just one argument to copy from, but as soon as I entered the second one the special handling of * was not applied anymore and that resulted in me having only files from archive-b and nothing else.

Earlier iteration of said CopyAction I had the 'to' argument as './' but let's now talk about that :)
