### ISSUE TITLE
How to work with multiselect choices question?

### ISSUE THREAD

**Issue by GiuseppeCSI** [factorial-io/phabalicious#217]
I am trying to scaffold a new app and I have a question for the user to select a bunch of components from a multiple choices question. Now, I've noticed that the answers to the questions can be used in the scaffold section as %yourkey.0%, %yourkey.1% etc based on how many choices you selected. My goal is to add the component only if it's selected, so my question is: is there any kind of IF statement for the scaffold or some other way to execute the command only if %yourkey.1% exist? Because right now referring to, for example, %yourkey.1% throws an error and blocks the process if it doesn't exist.
Practical example.
This is the question I ask:
```
yourkey:
  question: What fruits do you want to buy
  type: choices
  multiselect: true
  choices:
    - Apples
    - Oranges
    - Lemons
    - Papayas
    - Coconuts
```
I want the scaffolding section to create a directory for each of the selected options. So it would look something like this

```
scaffold:
  - mkdir %yourkey.0%
  - mkdir %yourkey.1%

```
How can I do this without knowing how many choices the user will make? Is there an IF statement or a way to check if, for example, %yourkey.1% exist without breaking the scaffold execution?

I'm sorry if it's a dumb question, but the docs are not clear at all on the use of values from questions
