### ISSUE TITLE
script-deployments do not work

### ISSUE THREAD

**Issue by stmh** [factorial-io/phabalicious#31]
running scripts for deplyoment do not work:
```
hosts:
  test: 
    deploy:
      - echo "running deployment"
```
You can workaround by rename it to "deployFinished"
