### ISSUE TITLE
host- and task-specific scripts do not get executed

### ISSUE THREAD

**Issue by stmh** [factorial-io/phabalicious#4]
A config similar to this will not work when running for example the `reset`-task

```
scripts:
  test:
    - echo "Success"

hosts:
  test:
    type: dev
    rootFolder: /some-root-folder
    needs: 
      - drush
      - scripts
    reset:
      - execute(script, test)
```
